### ISSUE TITLE
--multi-class  option

### ISSUE THREAD

**Issue by lombardata** [akarazniewicz/cocosplit#10]
I tried to use this repository to split a dataset of annotated images in instance segmentation (there are about 30 classes in the problem) and I noticed that the same image can be present in the training and test set.
is this normal?
Is splitting done on the basis of annotations and not on the basis of images (so an image with multiple annotations can be in the training and test set)?
Thank you !

**Comment by Lineker98** [comment]
i had the same problem and i don't know how to solve

**Comment by barrendo** [comment]
it does not work. Here is an alternative that worked for me:
https://www.kaggle.com/code/backtracking/smart-data-split-train-eval-for-object-detection/notebook 
however you have to change your annotation to csv format.

**Comment by lombardata** [comment]
finally I've found this library :
https://github.com/pylabel-project
and it works pretty well !
